# faz17_engine.py
"""Market enrichment engine for the HoopBrain bot. This module integrates with The Odds API v4 to pull real-time betting market data. The API documentation (https://the-odds-api.com/liveapi/guides/v4/) shows that odds are requested via the ``/v4/sports/{sport}/odds`` endpoint using parameters such as ``regions``, ``markets`` and ``oddsFormat``. The API responds with a list of events, each containing a list of bookmakers and markets.

For totals (over/under) markets, the ``point`` field of the ``Over`` outcome represents the bookmaker's total line. This engine queries the Odds API using configurable regions, markets and format. It then matches the home and away team names against the event data and extracts the totals line. The result is stored on the ``core.market`` object with an edge hint comparing the market line against the predicted full-time band.

If no matching event or totals market is found, the ``status`` is set to ``NO_MARKET``.
"""

import aiohttp
import os
from typing import Optional
from faz13_engine import Faz13CoreOutput

class Faz17Engine:
    """Retrieve over/under market lines from The Odds API and enrich core output."""

    def __init__(self, odds_api_key: str, odds_base: str) -> None:
        """Create a new market enrichment engine.

        Args:
            odds_api_key: Your API key for The Odds API.
            odds_base: Base URL for the API (e.g.
                ``https://api.the-odds-api.com/v4``).

        Additional parameters ``ODDS_REGIONS``, ``ODDS_MARKETS`` and ``ODDS_FORMAT``
        can be set as environment variables to customise the regions (e.g.
        ``us,eu``), markets (comma separated list) and odds format (``decimal``
        or ``american``) respectively.
        """
        self.key = odds_api_key
        self.base = odds_base.rstrip("/")
        # Read optional parameters from environment or fall back to sensible defaults
        self.regions = os.getenv("ODDS_REGIONS", "us")
        self.markets = os.getenv("ODDS_MARKETS", "totals,spreads")
        self.odds_format = os.getenv("ODDS_FORMAT", "decimal")
        self.session: Optional[aiohttp.ClientSession] = None

    async def _session(self) -> aiohttp.ClientSession:
        """Lazily create or return the aiohttp client session."""
        if not self.session or self.session.closed:
            self.session = aiohttp.ClientSession()
        return self.session

    @staticmethod
    def _norm(s: str) -> str:
        """Normalise a team name by lowercasing, stripping generic tokens and removing non-alphanumeric characters.

        This enables fuzzy matching between the user-provided team names and those returned by the Odds API.
        """
        s = s or ""
        lower = s.lower()
        for token in ("basketball", "basket", "bk", "bc", "club"):
            lower = lower.replace(token, "")
        return "".join(ch for ch in lower if ch.isalnum())

    async def enrich_with_market(self, core: Faz13CoreOutput) -> Faz13CoreOutput:
        """Populate ``core.market`` with totals data from The Odds API, if available.

        The function builds a request to the ``/v4/sports/{sport}/odds`` endpoint using the configured
        regions, markets and odds format. It then attempts to find an event whose home/away teams
        match the fixture under analysis. If a totals market is present, the first 'Over' outcome
        is used to derive the total line. An edge hint is generated by comparing the line against
        the predicted full-time band. When no matching event or totals market can be found,
        ``core.market`` is set to ``{"status": "NO_MARKET"}``.
        """
        # Determine sport key based on league; default to NBA
        league_upper = (core.ctx.league or "").upper()
        sport_key = "basketball_euroleague" if "EURO" in league_upper else "basketball_nba"

        url = f"{self.base}/sports/{sport_key}/odds"
        params = {
            "apiKey": self.key,
            "regions": self.regions,
            "markets": self.markets,
            "oddsFormat": self.odds_format,
        }

        # Fetch data
        session = await self._session()
        try:
            async with session.get(url, params=params) as resp:
                data = await resp.json()
        except Exception:
            core.market = {"status": "NO_MARKET"}
            return core

        # Normalised team names for matching
        nh, na = self._norm(core.ctx.home), self._norm(core.ctx.away)

        for event in data:
            # Eğer event dict değilse (örneğin string ise) atla
            if not hasattr(event, "get"):
                continue

            h = self._norm(event.get("home_team", ""))
            a = self._norm(event.get("away_team", ""))

            if not nh or not na:
                continue

            # Match fixture irrespective of home/away ordering
            if (nh in h and na in a) or (nh in a and na in h):
                selected_total = None
                selected_book = None

                # Search all bookmakers for a totals market
                for bookmaker in event.get("bookmakers", []):
                    for market in bookmaker.get("markets", []):
                        if market.get("key") == "totals":
                            for outcome in market.get("outcomes", []):
                                # Look for Over outcome as per API examples
                                name = (outcome.get("name") or "").lower()
                                if name.startswith("over") or name.startswith("üst"):
                                    selected_total = outcome.get("point")
                                    selected_book = bookmaker
                                    break
                        if selected_total is not None:
                            break
                    if selected_total is not None:
                        break

                if selected_total is not None:
                    # Derive edge hint by comparing to predicted band
                    lo, hi = (0, 0)
                    if isinstance(core.total_band, (list, tuple)) and len(core.total_band) == 2:
                        lo, hi = core.total_band

                    edge_hint = "Line yakın → net edge yok"
                    if isinstance(selected_total, (int, float)):
                        if selected_total > hi + 2:
                            edge_hint = "Line yüksek → ALT eğilimi"
                        elif selected_total < lo - 2:
                            edge_hint = "Line düşük → ÜST eğilimi"

                    core.market = {
                        "status": "OK",
                        "sport_key": sport_key,
                        "market_total": selected_total,
                        "book": selected_book.get("title") or selected_book.get("key") if selected_book else None,
                        "edge_hint": edge_hint,
                    }
                    return core

        # If no match found
        core.market = {"status": "NO_MARKET"}
        return core 
